// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXUb2sLJhUN6ZVQLNF-at429-kUGHq4s',
    appId: '1:902627334357:web:6e09a90f6a24db28fcea5c',
    messagingSenderId: '902627334357',
    projectId: 'appjam-group13-e4701',
    authDomain: 'appjam-group13-e4701.firebaseapp.com',
    storageBucket: 'appjam-group13-e4701.appspot.com',
    measurementId: 'G-K2XJDRX1ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGuJZDoqFTetMn8ivm9GtbfX8b-J7qes',
    appId: '1:902627334357:android:140767023927724cfcea5c',
    messagingSenderId: '902627334357',
    projectId: 'appjam-group13-e4701',
    storageBucket: 'appjam-group13-e4701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJA3yWVjX2SXFEsv1jyRnAS5yCFu5K94',
    appId: '1:902627334357:ios:aa680527f40b1fe9fcea5c',
    messagingSenderId: '902627334357',
    projectId: 'appjam-group13-e4701',
    storageBucket: 'appjam-group13-e4701.appspot.com',
    iosBundleId: 'com.example.appjamGroup13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJA3yWVjX2SXFEsv1jyRnAS5yCFu5K94',
    appId: '1:902627334357:ios:b5783c919f3c62acfcea5c',
    messagingSenderId: '902627334357',
    projectId: 'appjam-group13-e4701',
    storageBucket: 'appjam-group13-e4701.appspot.com',
    iosBundleId: 'com.example.appjamGroup13.RunnerTests',
  );
}
